// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ColorScreen = NULL;
lv_obj_t * ui_ColorLabel = NULL;
lv_obj_t * ui_ColorImage = NULL;
// event funtions

// build funtions

void ui_ColorScreen_screen_init(void)
{
    ui_ColorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ColorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ColorLabel = lv_label_create(ui_ColorScreen);
    lv_obj_set_width(ui_ColorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ColorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ColorLabel, 0);
    lv_obj_set_y(ui_ColorLabel, -104);
    lv_obj_set_align(ui_ColorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ColorLabel, "Color");
    lv_obj_set_style_text_font(ui_ColorLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorImage = lv_img_create(ui_ColorScreen);
    lv_img_set_src(ui_ColorImage, &ui_img_1695996548);
    lv_obj_set_width(ui_ColorImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ColorImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ColorImage, 3);
    lv_obj_set_y(ui_ColorImage, 15);
    lv_obj_set_align(ui_ColorImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ColorImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ColorImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ColorImage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ColorImage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ColorScreen_screen_destroy(void)
{
    if(ui_ColorScreen) lv_obj_del(ui_ColorScreen);

    // NULL screen variables
    ui_ColorScreen = NULL;
    ui_ColorLabel = NULL;
    ui_ColorImage = NULL;

}
