// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COLORSCREEN_H
#define UI_COLORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ColorScreen
extern void ui_ColorScreen_screen_init(void);
extern void ui_ColorScreen_screen_destroy(void);
extern lv_obj_t * ui_ColorScreen;
extern lv_obj_t * ui_ColorLabel;
extern lv_obj_t * ui_ColorImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

