// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HUMSOILSCREEN_H
#define UI_HUMSOILSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HumSoilScreen
extern void ui_HumSoilScreen_screen_init(void);
extern void ui_HumSoilScreen_screen_destroy(void);
extern lv_obj_t * ui_HumSoilScreen;
extern lv_obj_t * ui_Lux1;
extern lv_obj_t * ;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

