// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_HumSoilScreen = NULL;
lv_obj_t * ui_Lux1 = NULL;
lv_obj_t * ui_LuxVar1 = NULL;
// event funtions

// build funtions

void ui_HumSoilScreen_screen_init(void)
{
    ui_HumSoilScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HumSoilScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux1 = lv_label_create(ui_HumSoilScreen);
    lv_obj_set_width(ui_Lux1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lux1, 2);
    lv_obj_set_y(ui_Lux1, -52);
    lv_obj_set_align(ui_Lux1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lux1, "Humedad\nde \nsuelo");
    lv_obj_set_style_text_align(ui_Lux1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lux1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LuxVar1 = lv_label_create(ui_HumSoilScreen);
    lv_obj_set_width(ui_LuxVar1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxVar1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxVar1, 3);
    lv_obj_set_y(ui_LuxVar1, 33);
    lv_obj_set_align(ui_LuxVar1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxVar1, "---%");
    lv_obj_set_style_text_font(ui_LuxVar1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HumSoilScreen_screen_destroy(void)
{
    if(ui_HumSoilScreen) lv_obj_del(ui_HumSoilScreen);

    // NULL screen variables
    ui_HumSoilScreen = NULL;
    ui_Lux1 = NULL;
    ui_LuxVar1 = NULL;

}
