// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LUXSCREEN_H
#define UI_LUXSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LuxScreen
extern void ui_LuxScreen_screen_init(void);
extern void ui_LuxScreen_screen_destroy(void);
extern lv_obj_t * ui_LuxScreen;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_LuxVar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

