// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_LuxScreen = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_LuxVar = NULL;
// event funtions

// build funtions

void ui_LuxScreen_screen_init(void)
{
    ui_LuxScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LuxScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_LuxScreen, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_LuxScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -77);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Luminosidad\n");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LuxVar = lv_label_create(ui_LuxScreen);
    lv_obj_set_width(ui_LuxVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxVar, -1);
    lv_obj_set_y(ui_LuxVar, 7);
    lv_obj_set_align(ui_LuxVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxVar, "--");
    lv_obj_set_style_text_align(ui_LuxVar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_LuxScreen_screen_destroy(void)
{
    if(ui_LuxScreen) lv_obj_del(ui_LuxScreen);

    // NULL screen variables
    ui_LuxScreen = NULL;
    ui_Label3 = NULL;
    ui_LuxVar = NULL;

}
