// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Logo = NULL;
lv_obj_t * ui_Titulo = NULL;
lv_obj_t * ui_Kimeltuwe = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logo = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Logo, &ui_img_1249217846);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 104
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 103
    lv_obj_set_x(ui_Logo, 1);
    lv_obj_set_y(ui_Logo, -56);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Titulo = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Titulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Titulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Titulo, 3);
    lv_obj_set_y(ui_Titulo, 65);
    lv_obj_set_align(ui_Titulo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Titulo, "Sistema\nde\nMonitoreo");
    lv_obj_set_style_text_align(ui_Titulo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Titulo, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Kimeltuwe = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Kimeltuwe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kimeltuwe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kimeltuwe, 0);
    lv_obj_set_y(ui_Kimeltuwe, -138);
    lv_obj_set_align(ui_Kimeltuwe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Kimeltuwe, "Kimeltuwe Lof Tech");
    lv_obj_set_style_text_color(ui_Kimeltuwe, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Kimeltuwe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Kimeltuwe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Logo = NULL;
    ui_Titulo = NULL;
    ui_Kimeltuwe = NULL;

}
