// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_RAINSCREEN_H
#define UI_RAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RainScreen
extern void ui_RainScreen_screen_init(void);
extern void ui_RainScreen_screen_destroy(void);
extern lv_obj_t * ui_RainScreen;
extern lv_obj_t * ui_RainLabel;
extern lv_obj_t * ui_RainVar;
extern lv_obj_t * ui_RainArc;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

