// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_RainScreen = NULL;
lv_obj_t * ui_RainLabel = NULL;
lv_obj_t * ui_RainVar = NULL;
lv_obj_t * ui_RainArc = NULL;
// event funtions

// build funtions

void ui_RainScreen_screen_init(void)
{
    ui_RainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RainLabel = lv_label_create(ui_RainScreen);
    lv_obj_set_width(ui_RainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainLabel, 2);
    lv_obj_set_y(ui_RainLabel, -87);
    lv_obj_set_align(ui_RainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RainLabel, "Lluvia");
    lv_obj_set_style_text_align(ui_RainLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RainLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RainVar = lv_label_create(ui_RainScreen);
    lv_obj_set_width(ui_RainVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainVar, 6);
    lv_obj_set_y(ui_RainVar, 50);
    lv_obj_set_align(ui_RainVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RainVar, "-- %");
    lv_obj_set_style_text_align(ui_RainVar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RainVar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RainArc = lv_arc_create(ui_RainScreen);
    lv_obj_set_width(ui_RainArc, 134);
    lv_obj_set_height(ui_RainArc, 132);
    lv_obj_set_x(ui_RainArc, 3);
    lv_obj_set_y(ui_RainArc, 54);
    lv_obj_set_align(ui_RainArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_RainArc, 50);

}

void ui_RainScreen_screen_destroy(void)
{
    if(ui_RainScreen) lv_obj_del(ui_RainScreen);

    // NULL screen variables
    ui_RainScreen = NULL;
    ui_RainLabel = NULL;
    ui_RainVar = NULL;
    ui_RainArc = NULL;

}
