// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SoilScreen = NULL;
lv_obj_t * ui_SoilLabel = NULL;
lv_obj_t * ui_SoilArc = NULL;
lv_obj_t * ui_SoilVar = NULL;
// event funtions

// build funtions

void ui_SoilScreen_screen_init(void)
{
    ui_SoilScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SoilScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SoilLabel = lv_label_create(ui_SoilScreen);
    lv_obj_set_width(ui_SoilLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoilLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoilLabel, 1);
    lv_obj_set_y(ui_SoilLabel, -85);
    lv_obj_set_align(ui_SoilLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoilLabel, "Humedad\nde\nSuelo");
    lv_obj_set_style_text_align(ui_SoilLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoilLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilArc = lv_arc_create(ui_SoilScreen);
    lv_obj_set_width(ui_SoilArc, 134);
    lv_obj_set_height(ui_SoilArc, 134);
    lv_obj_set_x(ui_SoilArc, 2);
    lv_obj_set_y(ui_SoilArc, 53);
    lv_obj_set_align(ui_SoilArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_SoilArc, 50);

    ui_SoilVar = lv_label_create(ui_SoilScreen);
    lv_obj_set_width(ui_SoilVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoilVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoilVar, 3);
    lv_obj_set_y(ui_SoilVar, 50);
    lv_obj_set_align(ui_SoilVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoilVar, "-- %");
    lv_obj_set_style_text_font(ui_SoilVar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SoilScreen_screen_destroy(void)
{
    if(ui_SoilScreen) lv_obj_del(ui_SoilScreen);

    // NULL screen variables
    ui_SoilScreen = NULL;
    ui_SoilLabel = NULL;
    ui_SoilArc = NULL;
    ui_SoilVar = NULL;

}
