// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SOILSCREEN_H
#define UI_SOILSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SoilScreen
extern void ui_SoilScreen_screen_init(void);
extern void ui_SoilScreen_screen_destroy(void);
extern lv_obj_t * ui_SoilScreen;
extern lv_obj_t * ui_SoilLabel;
extern lv_obj_t * ui_SoilArc;
extern lv_obj_t * ui_SoilVar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

