// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TempHumScreen = NULL;
lv_obj_t * ui_TemperaturaLabel = NULL;
lv_obj_t * ui_HumedadLabel = NULL;
lv_obj_t * ui_TempVar = NULL;
lv_obj_t * ui_HumidityArc = NULL;
lv_obj_t * ui_HumidityVar = NULL;
// event funtions

// build funtions

void ui_TempHumScreen_screen_init(void)
{
    ui_TempHumScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TempHumScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperaturaLabel = lv_label_create(ui_TempHumScreen);
    lv_obj_set_width(ui_TemperaturaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperaturaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperaturaLabel, 1);
    lv_obj_set_y(ui_TemperaturaLabel, -108);
    lv_obj_set_align(ui_TemperaturaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperaturaLabel, "Temperatura");
    lv_obj_set_style_text_align(ui_TemperaturaLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperaturaLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumedadLabel = lv_label_create(ui_TempHumScreen);
    lv_obj_set_width(ui_HumedadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumedadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumedadLabel, 1);
    lv_obj_set_y(ui_HumedadLabel, 26);
    lv_obj_set_align(ui_HumedadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumedadLabel, "Humedad");
    lv_obj_set_style_text_align(ui_HumedadLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumedadLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempVar = lv_label_create(ui_TempHumScreen);
    lv_obj_set_width(ui_TempVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempVar, 2);
    lv_obj_set_y(ui_TempVar, -50);
    lv_obj_set_align(ui_TempVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempVar, "-- °C");
    lv_obj_set_style_text_align(ui_TempVar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempVar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityArc = lv_arc_create(ui_TempHumScreen);
    lv_obj_set_width(ui_HumidityArc, 100);
    lv_obj_set_height(ui_HumidityArc, 102);
    lv_obj_set_x(ui_HumidityArc, 2);
    lv_obj_set_y(ui_HumidityArc, 100);
    lv_obj_set_align(ui_HumidityArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_HumidityArc, 50);
    lv_obj_set_style_arc_width(ui_HumidityArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_HumidityArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HumidityVar = lv_label_create(ui_TempHumScreen);
    lv_obj_set_width(ui_HumidityVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityVar, 5);
    lv_obj_set_y(ui_HumidityVar, 96);
    lv_obj_set_align(ui_HumidityVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityVar, "-- %");
    lv_obj_set_style_text_align(ui_HumidityVar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityVar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TempHumScreen_screen_destroy(void)
{
    if(ui_TempHumScreen) lv_obj_del(ui_TempHumScreen);

    // NULL screen variables
    ui_TempHumScreen = NULL;
    ui_TemperaturaLabel = NULL;
    ui_HumedadLabel = NULL;
    ui_TempVar = NULL;
    ui_HumidityArc = NULL;
    ui_HumidityVar = NULL;

}
