// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TdsScreen = NULL;
lv_obj_t * ui_TdsLabel = NULL;
lv_obj_t * ui_TdsVar = NULL;
// event funtions

// build funtions

void ui_TdsScreen_screen_init(void)
{
    ui_TdsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TdsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TdsLabel = lv_label_create(ui_TdsScreen);
    lv_obj_set_width(ui_TdsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TdsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TdsLabel, 1);
    lv_obj_set_y(ui_TdsLabel, -72);
    lv_obj_set_align(ui_TdsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TdsLabel, "TDS");
    lv_obj_set_style_text_align(ui_TdsLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TdsLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TdsVar = lv_label_create(ui_TdsScreen);
    lv_obj_set_width(ui_TdsVar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TdsVar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TdsVar, 0);
    lv_obj_set_y(ui_TdsVar, 3);
    lv_obj_set_align(ui_TdsVar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TdsVar, "----");
    lv_obj_set_style_text_align(ui_TdsVar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TdsVar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TdsScreen_screen_destroy(void)
{
    if(ui_TdsScreen) lv_obj_del(ui_TdsScreen);

    // NULL screen variables
    ui_TdsScreen = NULL;
    ui_TdsLabel = NULL;
    ui_TdsVar = NULL;

}
