// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TDSSCREEN_H
#define UI_TDSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TdsScreen
extern void ui_TdsScreen_screen_init(void);
extern void ui_TdsScreen_screen_destroy(void);
extern lv_obj_t * ui_TdsScreen;
extern lv_obj_t * ui_TdsLabel;
extern lv_obj_t * ui_TdsVar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

