// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TEMPHUMSCREEN_H
#define UI_TEMPHUMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TempHumScreen
extern void ui_TempHumScreen_screen_init(void);
extern void ui_TempHumScreen_screen_destroy(void);
extern lv_obj_t * ui_TempHumScreen;
extern lv_obj_t * ui_TemperaturaLabel;
extern lv_obj_t * ui_HumedadLabel;
extern lv_obj_t * ui_TempVar;
extern lv_obj_t * ui_HumidityArc;
extern lv_obj_t * ui_HumidityVar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

